import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container:{
        backgroundColor:'#F0F0F7',
        flex:1,
        justifyContent:'center',
        paddingHorizontal:20,
    },
    header:{
        width:'100%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        top:-70
    },
    containerIndicators:{
        width:20,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
    },
    inactiveIndicator:{
        width:4,
        height:4,
        borderRadius:2,
        backgroundColor:'#C1BCCC',
    },
    activeIndicator:{
        width:4,
        height:4,
        borderRadius:2,
        backgroundColor:'#8257E5',
    },
    emailAndPassword:{
        fontFamily:'Poppins_600SemiBold',
        fontSize:24,
        lineHeight:26,
        color:'#32264D',
        marginTop:180,
    },
    form:{
        width:'100%',
        marginTop:20,
        alignItems:'center',
        justifyContent:'center',
    },
    inputEmailBlock:{
        width:310,
        height:64,
        backgroundColor:'#FAFAFC',
        borderWidth:1,
        borderStyle:'solid',
        borderColor:'#E6E6F0',
        borderTopRightRadius:8,
        borderTopLeftRadius:8,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
    },
    inputPasswordBlock:{
        width:310,
        height:64,
        backgroundColor:'#FAFAFC',
        borderWidth:1,
        borderStyle:'solid',
        borderColor:'#E6E6F0',
        borderBottomRightRadius:8,
        borderBottomLeftRadius:8,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
    },  
    input:{
        width:'80%',
        height:'100%',
        paddingHorizontal:10,
    },
    buttonShowsPassword:{
        alignItems:'center',
        justifyContent:'center',
        width:'20%',
        height:'100%',
    },
    errorMessage:{
        color:'#ff1439',
        fontWeight:'bold',
        marginTop:15,
    },
    inactiveSubmitButton:{
        width:310,
        height:56,
        borderRadius:8,
        marginTop:15,
        backgroundColor:'#DCDCE5',
        alignItems:'center',
        justifyContent:'center',
    },
    inactiveTextSubmitButton:{
        fontFamily:'Archivo_400Regular',
        fontSize:16,
        lineHeight:26,
        color:'#9C98A6',
    },
    activeSubmitButton:{
        width:310,
        height:56,
        borderRadius:8,
        marginTop:15,
        backgroundColor:'#04D361',
        alignItems:'center',
        justifyContent:'center',
    },
    activeTextSubmitButton:{
        fontFamily:'Archivo_400Regular',
        fontSize:16,
        lineHeight:26,
        color:'#FFFFFF',
    }
})

export default styles;