import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    wrapper:{
        flex:1,
    },
    topContainer:{
        width:'100%',
        height:'45%',
        backgroundColor:'#8257E5',
        alignItems:'center',
        justifyContent:'center',
    },
    backgroundImage:{
        width:238.66,
        height:266.21,
        alignItems:'center',
        justifyContent:'center',
    },
    sloganContainer:{
        width:'70%',
        marginTop:10,
    },
    slogan:{
        width:110.04,
        height:28,
    },
    bottomContainer:{
        width:'100%',
        height:'55%',
        paddingHorizontal:20,
        paddingTop:25,
        backgroundColor:'#F0F0F7',
    },
    forgotYourPassword:{
        fontFamily:'Poppins_600SemiBold',
        fontSize:24,
        lineHeight:34,
        color:'#32264D',
        marginTop:40,
    },
    info:{
        fontFamily:'Poppins_400Regular',
        fontSize:14,
        lineHeight:24,
        color:'#6A6180',
        marginTop:20,
    },
    form:{
        width:'100%',
        marginTop:30,
        alignItems:'center',
        justifyContent:'center',
    },
    input:{
        width:310,
        height:64,
        paddingHorizontal:15,
        backgroundColor:'#FAFAFC',
        borderWidth:1,
        borderStyle:'solid',
        borderColor:'#E6E6F0',
        borderRadius:8,
        fontFamily:'Poppins_400Regular',
    },
    errorMessage:{
        color:'#ff1439',
        fontWeight:'bold',
        marginTop:15,
    },
    inactiveButton:{
        width:310,
        height:56,
        marginTop:20,
        borderRadius:8,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#DCDCE5',
    },
    inactiveTextButton:{
        fontFamily:'Archivo_400Regular',
        fontSize:16,
        lineHeight:26,
        color:'#9C98A6',
    },
    activeButton:{
        width:310,
        height:56,
        marginTop:20,
        borderRadius:8,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#04D361',
    },
    activeTextButton:{
        fontFamily:'Archivo_400Regular',
        fontSize:16,
        lineHeight:26,
        color:'#FFF',
    },
});

export default styles;