import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    wrapper:{
        backgroundColor:'#F0F0F7',
        flex:1,
    },
    topContainer:{
        width:'100%',
        height:'50%',
        paddingHorizontal:20,
        justifyContent:'center',     
    },
    header:{
        width:'100%',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
    },
    containerIndicators:{
        width:20,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
    },
    activeIndicator:{
        width:4,
        height:4,
        borderRadius:2,
        backgroundColor:'#8257E5',
    },
    inactiveIndicator:{
        width:4,
        height:4,
        borderRadius:2,
        backgroundColor:'#C1BCCC',
    },
    createAccount:{
        fontFamily:'Poppins_600SemiBold',
        fontSize:32,
        lineHeight:42,
        color:'#32264D',
        marginTop:40,
    },
    info:{
        fontFamily:'Poppins_400Regular',
        fontSize:14,
        lineHeight:24,
        color:'#6A6180',
        marginTop:15
    },
    bottomContainer:{
        width:'100%',
        height:'50%',
        paddingHorizontal:20,
        justifyContent:'center',
    },
    whoAreYou:{
        fontFamily:'Poppins_600SemiBold',
        fontSize:24,
        lineHeight:26,
        color:'#32264D',
        marginTop:20,
    },
    form:{
        width:'100%',
        marginTop:20,
        alignItems:'center',
        justifyContent:'center',
        
    },
    input:{
        width:'100%',
        height:'100%',
        paddingHorizontal:10,
    },
    inputNameBlock:{
        width:310,
        height:64,
        backgroundColor:'#FAFAFC',
        borderWidth:1,
        borderStyle:'solid',
        borderColor:'#E6E6F0',
        borderTopRightRadius:8,
        borderTopLeftRadius:8,
        alignItems:'center',
        justifyContent:'center',
    },
    inputSurnameBlock:{
        width:310,
        height:64,
        backgroundColor:'#FAFAFC',
        borderWidth:1,
        borderStyle:'solid',
        borderColor:'#E6E6F0',
        borderBottomRightRadius:8,
        borderBottomLeftRadius:8,
        alignItems:'center',
        justifyContent:'center',
    },
    errorMessage:{
        fontWeight:'bold',
        color:'#ff1439',
        marginTop:20,
    },  
    inactiveSubmitButton:{
        width:310,
        height:56,
        borderRadius:8,
        marginTop:15,
        backgroundColor:'#DCDCE5',
        alignItems:'center',
        justifyContent:'center',
    },
    inactiveTextSubmitButton:{
        fontFamily:'Archivo_400Regular',
        fontSize:16,
        lineHeight:26,
        color:'#9C98A6',
    },
    activeSubmitButton:{
        width:310,
        height:56,
        borderRadius:8,
        marginTop:15,
        backgroundColor:'#8257E5',
        alignItems:'center',
        justifyContent:'center',
    },
    activeTextSubmitButton:{
        fontFamily:'Archivo_400Regular',
        fontSize:16,
        lineHeight:26,
        color:'#FFFFFF',
    }
})

export default styles;